# Generated by Django 4.2.16 on 2026-04-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('source', models.CharField(choices=[('phone', '电话'), ('website', '网站'), ('app', 'APP'), ('wechat', '微信'), ('offline', '线下')], default='phone', max_length=20, verbose_name='工单来源')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='工单状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='紧急程度')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户电话')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户邮箱')),
                ('receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='受理人')),
                ('handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理人')),
                ('handle_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理部门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单类型',
                'verbose_name_plural': '工单类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='原处理人')),
                ('from_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='原处理部门')),
                ('to_handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='新处理人')),
                ('to_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='新处理部门')),
                ('transfer_reason', models.TextField(blank=True, null=True, verbose_name='转派原因')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '转派记录',
                'verbose_name_plural': '转派记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype', verbose_name='工单类型'),
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='原值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_histories', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '编辑历史记录',
                'verbose_name_plural': '编辑历史记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段显示名称')),
                ('field_code', models.CharField(max_length=100, verbose_name='字段代码')),
                ('field_type', models.CharField(choices=[('input', '输入框'), ('select', '下拉框'), ('textarea', '文本域')], default='input', max_length=20, verbose_name='控件类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('options', models.TextField(blank=True, null=True, verbose_name='选项值')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='占位符提示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tickets.tickettype', verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '自定义字段配置',
                'verbose_name_plural': '自定义字段配置',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('ticket_type', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='字段值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='tickets.customfield', verbose_name='自定义字段')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单自定义字段值',
                'verbose_name_plural': '工单自定义字段值',
                'unique_together': {('ticket', 'custom_field')},
            },
        ),
    ]
