# Generated by Django 4.2.16 on 2026-04-27 13:03

from django.db import migrations


def init_ticket_types(apps, schema_editor):
    TicketType = apps.get_model('tickets', 'TicketType')
    
    ticket_types = [
        {'name': '投诉', 'code': 'COMPLAINT', 'description': '用户投诉类工单'},
        {'name': '故障返修', 'code': 'REPAIR', 'description': '产品故障返修类工单'},
        {'name': '建议', 'code': 'SUGGESTION', 'description': '用户建议类工单'},
        {'name': '报表问题', 'code': 'REPORT_ISSUE', 'description': '报表相关问题工单'},
        {'name': '平台功能异常', 'code': 'PLATFORM_ERROR', 'description': '平台功能异常类工单'},
        {'name': '检测', 'code': 'INSPECTION', 'description': '产品检测类工单'},
        {'name': '预约上门服务', 'code': 'APPOINTMENT', 'description': '预约上门服务类工单'},
    ]
    
    for item in ticket_types:
        TicketType.objects.get_or_create(
            code=item['code'],
            defaults={
                'name': item['name'],
                'description': item['description'],
                'is_active': True
            }
        )


def reverse_init_ticket_types(apps, schema_editor):
    TicketType = apps.get_model('tickets', 'TicketType')
    codes = ['COMPLAINT', 'REPAIR', 'SUGGESTION', 'REPORT_ISSUE', 
             'PLATFORM_ERROR', 'INSPECTION', 'APPOINTMENT']
    TicketType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_ticket_types, reverse_init_ticket_types),
    ]
