# Generated by Django 4.2.16 on 2026-04-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_init_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='dependent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='tickets.customfield', verbose_name='前置依赖字段'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='dependent_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='依赖选项值'),
        ),
    ]
